jobs:
  my_job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, arm64]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Print architecture
          run: echo ${{ matrix.arch }}

